### ISSUE TITLE
1.0 Umbrella

### ISSUE THREAD

**Issue by danez** [reactjs/react-tabs#125]
- [x] Remove bower support
- [x] Use ES6 classes
- [ ] Split controlled behavior from non-controlled (#80)
- [ ] Fix isomorphic problems
- [x] Cleanup exports
- [x] Make styling optional

**Comment by LeoAJ** [comment]
Hi @danez 

I can help **Use ES6 classes**, will submit PR later. Thanks!

**Comment by dmitry** [comment]
Responsiveness must have in 1.0: https://github.com/reactjs/react-tabs/issues/142
